general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
# Changed to JetBrainsMono Nerd Font
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 15

[window]
padding.x = 14
padding.y = 14
decorations = "None"
# 30% transparency means an opacity of 0.7 (70% opaque)
opacity = 0.7
# Increases the startup size (measured in columns/lines, not pixels)
dimensions = { columns = 100, lines = 30 }

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" }
]
