log_level = "warn"
outputs = { Targets = ["eDP-1"] }
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [ [ "appLauncher", "Updates", "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [  "Tray", "Clock", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = "ó±—¼"
command = "walker"

[window_title]
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]

scale_factor = 1.5

success_color = "#8bd5a3"          # soft jade green
text_color = "#d7fbe8"             # pale jade-white

workspace_colors = [ 
  "#8bd5a3",  # jade green
  "#a6e3b1",  # light mint jade
  "#5bb98c"   # deeper moss green
]

[appearance.primary_color]
base = "#5bb98c"                   # Osaka jade core tone
text = "#0b1c13"                   # very dark green-black

[appearance.danger_color]
base = "#e78284"                   # muted red for contrast
weak = "#f2b6a0"                   # warm soft red

[appearance.background_color]
base = "#0b1c13"                   # near-black with a green tint
weak = "#142820"                   # dark moss green
strong = "#1f3a2f"                 # deeper forest green

[appearance.secondary_color]
base = "#10271e"                   # muted forest base
strong = "#19362c"                 # strong green-gray contrast

